package im.youtiao.android_client.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import im.youtiao.android_client.dao.Group;
import im.youtiao.android_client.dao.Bulletin;

import im.youtiao.android_client.dao.GroupDao;
import im.youtiao.android_client.dao.BulletinDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupDaoConfig;
    private final DaoConfig bulletinDaoConfig;

    private final GroupDao groupDao;
    private final BulletinDao bulletinDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        bulletinDaoConfig = daoConfigMap.get(BulletinDao.class).clone();
        bulletinDaoConfig.initIdentityScope(type);

        groupDao = new GroupDao(groupDaoConfig, this);
        bulletinDao = new BulletinDao(bulletinDaoConfig, this);

        registerDao(Group.class, groupDao);
        registerDao(Bulletin.class, bulletinDao);
    }
    
    public void clear() {
        groupDaoConfig.getIdentityScope().clear();
        bulletinDaoConfig.getIdentityScope().clear();
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public BulletinDao getBulletinDao() {
        return bulletinDao;
    }

}
